version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: observabilidad-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 5s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: observabilidad-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.133.0
    container_name: observabilidad-otel-collector
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yml:ro
    command: ["--config", "/etc/otelcol-contrib/config.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
      - "1777:1777"
      - "13133:13133"
    depends_on:
      elasticsearch:
        condition: service_healthy

  demo:
    image: demo
    container_name: demo_app
    build: .
    ports:
      - "8080:8080"
    environment:
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://otel-collector:4318/v1/traces
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
    depends_on:
      elasticsearch:
        condition: service_healthy
      otel-collector:
        condition: service_started

volumes:
  es_data:
